name: Axios

on:
  push:
    branches:
      - main
  schedule:
     - cron: '*/1 * * * *' # 每5分钟一次，测试用

jobs:
  axios-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call Auth API
        uses: actionsflow/axios@v1
        id: api
        with:
          url: https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/d4ad74d3-54ec-440c-8d84-ffe5dda848fb
          method: "POST"
          # basic-auth: "${{ secrets.username }}:${{ secrets.password }}"
      - run: echo ${{ steps.api.outputs.data }} # 打印数据
      # - run: echo ${{ steps.api.outputs.data.data.token }}

      #- name: Get current timestamp 获取当前时间戳
      #  id: get_timestamp
      #  run: echo "BUILD_TIME=$(date +'%s')" >> $GITHUB_ENV
      #- run: echo ${{ env.BUILD_TIME }}

      - name: Extract JSON Property 获取JSON数据
        id: extract-json
        run: |
          getToken=$(echo '${{ steps.api.outputs.data }}' | jq -r '.data.result.id')
          echo "token=$getToken" >> $GITHUB_ENV  # 添加到环境变量里
